package com.neoteric.exception;

public class ExceptionTest {

    public void calculateWithFinally(int numberOfTickets)throws Exception{

    }
}
